package model.eo.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 29 01:01:37 GMT 2018
// ---------------------------------------------------------------------
public interface AppModule
  extends ApplicationModule
{
  void insertDeptToDatabase(int deptId, String deptName);
}

