package model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 25 00:41:45 GMT 2018
// ---------------------------------------------------------------------
public interface EmployeesView
  extends ViewObject
{
  String getEmployeeFullName(int employeeId);
}

