package model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 08 02:16:54 GMT 2018
// ---------------------------------------------------------------------
public interface DepartmentsView
  extends ViewObject
{
  String getDeptNameCustomMethod(String deptId);
}

