package model.eo;

import model.eo.common.AppModule;

import model.vo.ProgrammaticDepartmentsViewImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 29 00:58:11 GMT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl
  extends ApplicationModuleImpl
  implements AppModule
{
  /**
   * This is the default constructor (do not remove).
   */
  public AppModuleImpl()
  {
  }

  /**
   * Container's getter for DepartmentsView1.
   * @return DepartmentsView1
   */
  public ViewObjectImpl getDepartmentsView1()
  {
    return (ViewObjectImpl) findViewObject("DepartmentsView1");
  }

  /**
   * Container's getter for ProgrammaticDepartmentsView1.
   * @return ProgrammaticDepartmentsView1
   */
  public ProgrammaticDepartmentsViewImpl getProgrammaticDepartmentsView1()
  {
    return (ProgrammaticDepartmentsViewImpl) findViewObject("ProgrammaticDepartmentsView1");
  }
  
  public void insertDeptToDatabase(int deptId, String deptName)
  {
    ViewObjectImpl deptVo = getDepartmentsView1();
    oracle.jbo.Row r = deptVo.createRow();
    r.setAttribute("DepartmentId", deptId);
    r.setAttribute("DepartmentName", deptName);
    deptVo.insertRow(r);
  }
}

