package model.vo;

import model.vo.common.EmployeesView;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.Key;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 25 00:35:59 GMT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl
  extends ViewObjectImpl
  implements EmployeesView
{
  /**
   * This is the default constructor (do not remove).
   */
  public EmployeesViewImpl()
  {
  }
  
  public String getEmployeeFullName(int employeeId)
  {
    Key empKey = new Key(new Object[] {employeeId});
    Row r = this.findByKey(empKey, 1)[0];
    String fullName = r.getAttribute("FirstName") + " " + r.getAttribute("LastName");
    return fullName;
  }
}

