package model.vo;

import oracle.jbo.server.ViewDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 24 23:36:28 GMT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewExRowImpl
  extends EmployeesViewRowImpl
{


  public static final int MAXUSAGECONST = 1;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    EmployeeFullName;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = ViewDefImpl.getMaxAttrConst("model.vo.EmployeesView");

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int EMPLOYEEFULLNAME = AttributesEnum.EmployeeFullName.index();

  /**
   * This is the default constructor (do not remove).
   */
  public EmployeesViewExRowImpl()
  {
  }

  /**
   * Gets the attribute value for the calculated attribute EmployeeFullName.
   * @return the EmployeeFullName
   */
  public String getEmployeeFullName()
  {
    return getFirstName() + " " + getLastName();
    //return (String) getAttributeInternal(EMPLOYEEFULLNAME);
  }
}

