package model.eo.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 25 00:34:42 GMT 2018
// ---------------------------------------------------------------------
public interface AppModule
  extends ApplicationModule
{
  String getDepartmentName(int deptId);
}

