package model.vo;

import model.vo.common.DepartmentsView;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 08 02:13:59 GMT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl
  extends ViewObjectImpl
  implements DepartmentsView
{
  /**
   * This is the default constructor (do not remove).
   */
  public DepartmentsViewImpl()
  {
  }
  
  public String getDeptNameCustomMethod(String deptId)
  {
    Key deptKey = new Key (new Object[] {deptId});
    Row r = this.findByKey(deptKey, 1)[0];
    return (String) r.getAttribute("DepartmentName");
  }
}

