package model.eo;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 02 23:38:17 GMT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl
  extends ApplicationModuleImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public AppModuleImpl()
  {
  }

  /**
   * Container's getter for DepartmentsView1.
   * @return DepartmentsView1
   */
  public ViewObjectImpl getDepartmentsView1()
  {
    return (ViewObjectImpl) findViewObject("DepartmentsView1");
  }
  
  public String getCustomDeptName(int deptId)
  {
    Key deptKey = new Key(new Object []{deptId});
    Row r = getDepartmentsView1().findByKey(deptKey, 1)[0];
    return (String) r.getAttribute("DepartmentName");
  }
}

