package model.vo;

import java.math.BigDecimal;

import model.common.ModelUtil;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 30 00:22:26 GMT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public EmployeesViewImpl()
  {
  }

  /**
   * Returns the variable value for vcDeptIdParam.
   * @return variable value for vcDeptIdParam
   */
  public Integer getvcDeptIdParam()
  {
    return (Integer) ensureVariableManager().getVariableValue("vcDeptIdParam");
  }

  /**
   * Sets <code>value</code> for variable vcDeptIdParam.
   * @param value value to bind as vcDeptIdParam
   */
  public void setvcDeptIdParam(Integer value)
  {
    ensureVariableManager().setVariableValue("vcDeptIdParam", value);
  }

  /**
   * Returns the variable value for vcSalaryParam.
   * @return variable value for vcSalaryParam
   */
  public BigDecimal getvcSalaryParam()
  {
    return (BigDecimal) ensureVariableManager().getVariableValue("vcSalaryParam");
  }

  /**
   * Sets <code>value</code> for variable vcSalaryParam.
   * @param value value to bind as vcSalaryParam
   */
  public void setvcSalaryParam(BigDecimal value)
  {
    ensureVariableManager().setVariableValue("vcSalaryParam", value);
  }
  
  public void getEmpsForDept()
  {
    ViewCriteria vc = getViewCriteria("EmployeesForDeptViewCriteria");
    setvcDeptIdParam(Integer.parseInt(ModelUtil.getUserDeptId()));
    applyViewCriteria(vc);
    executeQuery();
  }
  
  public void getEmpsBySalary(double salary)
  {
    ViewCriteria vc = getViewCriteria("EmployeesBySalaryViewCriteria");
    setvcSalaryParam(new BigDecimal(salary));
    applyViewCriteria(vc);
    executeQuery();
  }


  @Override
  protected void executeQueryForCollection(Object object, Object[] object2, int i)
  {
    setWhereClause("Employees.SALARY >= 10000");
    super.executeQueryForCollection(object, object2, i);
  }


  @Override
  public void prepareRowSetForQuery(ViewRowSetImpl viewRowSetImpl)
  {
    //viewRowSetImpl.ensureVariableManager().setVariableValue("variableName", <value>); // to set bind variable
    super.prepareRowSetForQuery(viewRowSetImpl);
  }
}

